# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Main_Folder/School/Year_4/Capstone/pynq/pynq_test/pynq_test.srcs/sources_1/bd/matmult_ex/ip/matmult_ex_matmul_partition_0_0/matmult_ex_matmul_partition_0_0.xci
# IP: The module: 'matmult_ex_matmul_partition_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Main_Folder/School/Year_4/Capstone/pynq/pynq_test/pynq_test.gen/sources_1/bd/matmult_ex/ip/matmult_ex_matmul_partition_0_0/constraints/matmul_partition_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'matmult_ex_matmul_partition_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Main_Folder/School/Year_4/Capstone/pynq/pynq_test/pynq_test.srcs/sources_1/bd/matmult_ex/ip/matmult_ex_matmul_partition_0_0/matmult_ex_matmul_partition_0_0.xci
# IP: The module: 'matmult_ex_matmul_partition_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Main_Folder/School/Year_4/Capstone/pynq/pynq_test/pynq_test.gen/sources_1/bd/matmult_ex/ip/matmult_ex_matmul_partition_0_0/constraints/matmul_partition_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'matmult_ex_matmul_partition_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
