# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Main_Folder/School/Year_4/Capstone/pynq/PYNQ-Z2 v1.0.xdc

# Block Designs: bd/matmult_ex/matmult_ex.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==matmult_ex || ORIG_REF_NAME==matmult_ex} -quiet] -quiet

# IP: bd/matmult_ex/ip/matmult_ex_processing_system7_0_0/matmult_ex_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==matmult_ex_processing_system7_0_0 || ORIG_REF_NAME==matmult_ex_processing_system7_0_0} -quiet] -quiet

# IP: bd/matmult_ex/ip/matmult_ex_matmul_partition_0_0/matmult_ex_matmul_partition_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==matmult_ex_matmul_partition_0_0 || ORIG_REF_NAME==matmult_ex_matmul_partition_0_0} -quiet] -quiet

# IP: bd/matmult_ex/ip/matmult_ex_axi_smc_0/matmult_ex_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==matmult_ex_axi_smc_0 || ORIG_REF_NAME==matmult_ex_axi_smc_0} -quiet] -quiet

# IP: bd/matmult_ex/ip/matmult_ex_rst_ps7_0_100M_0/matmult_ex_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==matmult_ex_rst_ps7_0_100M_0 || ORIG_REF_NAME==matmult_ex_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/matmult_ex/ip/matmult_ex_xlconstant_0_0/matmult_ex_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==matmult_ex_xlconstant_0_0 || ORIG_REF_NAME==matmult_ex_xlconstant_0_0} -quiet] -quiet

# IP: bd/matmult_ex/ip/matmult_ex_xlconstant_0_1/matmult_ex_xlconstant_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==matmult_ex_xlconstant_0_1 || ORIG_REF_NAME==matmult_ex_xlconstant_0_1} -quiet] -quiet

# XDC: c:/Main_Folder/School/Year_4/Capstone/pynq/pynq_test/pynq_test.gen/sources_1/bd/matmult_ex/matmult_ex_ooc.xdc
