# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Main_Folder/School/Year_4/Capstone/pynq/pynq_test/pynq_test.srcs/sources_1/bd/matmult_ex/ip/matmult_ex_rst_ps7_0_100M_0/matmult_ex_rst_ps7_0_100M_0.xci
# IP: The module: 'matmult_ex_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Main_Folder/School/Year_4/Capstone/pynq/pynq_test/pynq_test.gen/sources_1/bd/matmult_ex/ip/matmult_ex_rst_ps7_0_100M_0/matmult_ex_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'matmult_ex_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Main_Folder/School/Year_4/Capstone/pynq/pynq_test/pynq_test.gen/sources_1/bd/matmult_ex/ip/matmult_ex_rst_ps7_0_100M_0/matmult_ex_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'matmult_ex_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Main_Folder/School/Year_4/Capstone/pynq/pynq_test/pynq_test.gen/sources_1/bd/matmult_ex/ip/matmult_ex_rst_ps7_0_100M_0/matmult_ex_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'matmult_ex_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Main_Folder/School/Year_4/Capstone/pynq/pynq_test/pynq_test.srcs/sources_1/bd/matmult_ex/ip/matmult_ex_rst_ps7_0_100M_0/matmult_ex_rst_ps7_0_100M_0.xci
# IP: The module: 'matmult_ex_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Main_Folder/School/Year_4/Capstone/pynq/pynq_test/pynq_test.gen/sources_1/bd/matmult_ex/ip/matmult_ex_rst_ps7_0_100M_0/matmult_ex_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'matmult_ex_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Main_Folder/School/Year_4/Capstone/pynq/pynq_test/pynq_test.gen/sources_1/bd/matmult_ex/ip/matmult_ex_rst_ps7_0_100M_0/matmult_ex_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'matmult_ex_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Main_Folder/School/Year_4/Capstone/pynq/pynq_test/pynq_test.gen/sources_1/bd/matmult_ex/ip/matmult_ex_rst_ps7_0_100M_0/matmult_ex_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'matmult_ex_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
